services:
  app:
    container_name: nodejs-app
    build: .
    ports:
      - "3000:3000"
    command: npm start
    environment:
      MONGODB_URL: "mongodb://mongo:27017/todos"
      NODE_ENV: production
      PORT: 3000
    expose:
      - 3000
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
